name 'chef_template'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures chef_template'
long_description 'Installs/Configures chef_template'
version '0.1.0'
