name 'Haproxy'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures Haproxy'
long_description 'Installs/Configures Haproxy'
version '0.1.0'
